In [1]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1)
A2 = np.array(l2)

print(f"{A1} * {A2} = {A1*A2}")

[1 2 3] * [4 5 6] = [ 4 10 18]


In [2]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1)
A2 = np.array(l2)

A = A1*A2

print(f"{A1} * {A2} = {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

[1 2 3] * [4 5 6] = [ 4 10 18]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (3,)


In [3]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1, np.int8)
A2 = np.array(l2, np.int8)

A = A1*A2

print(f"{A1} * {A2} = {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

[1 2 3] * [4 5 6] = [ 4 10 18]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int8
The dimension of an array: (3,)


In [4]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1, np.int8)
A2 = np.array(l2, np.int8)

A = A1*A2

print(f"{A1} * {A2} = {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

[1 2 3] * [4 5 6] = [ 4 10 18]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int8
The dimension of an array: (3,)
The size of an array: 3


In [5]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A = np.array((l1, l2))
print(f" The 2D array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The 2D array is : 
 [[1 2 3]
 [4 5 6]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (2, 3)
The size of an array: 6


In [6]:
A = np.array(([1,2,3,4,5]))
print(f" The 1D array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The 1D array is : 
 [1 2 3 4 5]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (5,)
The size of an array: 5


In [7]:
import numpy as np

A = np.array(([1,2,3,4,5], [2,3,4,5,6]))
print(f" The 2D array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The 2D array is : 
 [[1 2 3 4 5]
 [2 3 4 5 6]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (2, 5)
The size of an array: 10


In [8]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (4, 4)
The size of an array: 16


In [9]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The original array is : \n {A}")

A[1,2] = 10
print(f" The array after replacing : \n {A}")

 The original array is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The array after replacing : 
 [[ 1  2  3  4]
 [ 3  6 10  4]
 [ 1  2  9  4]
 [ 1  4  5  4]]


In [10]:
import numpy as np

A = np.zeros([5,5])
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: float64
The dimension of an array: (5, 5)
The size of an array: 25


In [11]:
import numpy as np

A = np.zeros([5])
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is : 
 [0. 0. 0. 0. 0.]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: float64
The dimension of an array: (5,)
The size of an array: 5


In [12]:
import numpy as np

A = np.arange(1,100)
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (99,)
The size of an array: 99


In [13]:
import numpy as np

A = np.arange(1,100,10)
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is : 
 [ 1 11 21 31 41 51 61 71 81 91]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (10,)
The size of an array: 10


In [14]:
import numpy as np

A = np.linspace(2,3,100)
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is : 
 [2.         2.01010101 2.02020202 2.03030303 2.04040404 2.05050505
 2.06060606 2.07070707 2.08080808 2.09090909 2.1010101  2.11111111
 2.12121212 2.13131313 2.14141414 2.15151515 2.16161616 2.17171717
 2.18181818 2.19191919 2.2020202  2.21212121 2.22222222 2.23232323
 2.24242424 2.25252525 2.26262626 2.27272727 2.28282828 2.29292929
 2.3030303  2.31313131 2.32323232 2.33333333 2.34343434 2.35353535
 2.36363636 2.37373737 2.38383838 2.39393939 2.4040404  2.41414141
 2.42424242 2.43434343 2.44444444 2.45454545 2.46464646 2.47474747
 2.48484848 2.49494949 2.50505051 2.51515152 2.52525253 2.53535354
 2.54545455 2.55555556 2.56565657 2.57575758 2.58585859 2.5959596
 2.60606061 2.61616162 2.62626263 2.63636364 2.64646465 2.65656566
 2.66666667 2.67676768 2.68686869 2.6969697  2.70707071 2.71717172
 2.72727273 2.73737374 2.74747475 2.75757576 2.76767677 2.77777778
 2.78787879 2.7979798  2.80808081 2.81818182 2.82828283 2.83838384
 2.84848485 2.85858586 2.86868687 2.87878788 

In [15]:
import numpy as np

A = np.identity(5)
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: float64
The dimension of an array: (5, 5)
The size of an array: 25


In [16]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The Matrix is : \n {A}")

print(f" The row wise sum is : {A.sum(axis=1)}")
print(f" The column wise sum is : {A.sum(axis=0)}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The row wise sum is : [10 16 16 14]
 The column wise sum is : [ 6 14 20 16]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (4, 4)
The size of an array: 16


In [17]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The Matrix is : \n {A}")

print(f" The transpose is : \n {A.T}")

 The Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The transpose is : 
 [[1 3 1 1]
 [2 6 2 4]
 [3 3 9 5]
 [4 4 4 4]]


In [18]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The 4x4 Matrix is : \n {A}")

print(f" The 8x2 matrix: \n {A.reshape(8,2)}")

 The 4x4 Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The 8x2 matrix: 
 [[1 2]
 [3 4]
 [3 6]
 [3 4]
 [1 2]
 [9 4]
 [1 4]
 [5 4]]


In [20]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The 4x4 Matrix is : \n {A}")

print(f" The 1D array from above matrix using ravel: \n {A.ravel()}")

 The 4x4 Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The 1D array from above matrix using ravel: 
 [1 2 3 4 3 6 3 4 1 2 9 4 1 4 5 4]


In [21]:
import numpy as np

a = [1, 16, 31, 4]

A = np.array(a)
print(f"The original array: {A}")

print(f"The index of maximum value in array is: {A.argmax()}")
print(f"The index of minimum value in array is: {A.argmin()}")
print(f"Sorted Indexes: {A.argsort()}")

The original array: [ 1 16 31  4]
The index of maximum value in array is: 2
The index of minimum value in array is: 0
Sorted Indexes: [0 3 1 2]


In [22]:
import numpy as np

f1=np.full((2,2),5)
f1

array([[5, 5],
       [5, 5]])

In [23]:
f2 = np.full((2,2), 3)
f2

array([[3, 3],
       [3, 3]])

In [24]:
a = np.vstack([f1, f2])
a

array([[5, 5],
       [5, 5],
       [3, 3],
       [3, 3]])

In [25]:
b = np.hstack([f1, f2])
b

array([[5, 5, 3, 3],
       [5, 5, 3, 3]])

In [26]:
a = np.column_stack([f1, f2])
a

array([[5, 5, 3, 3],
       [5, 5, 3, 3]])

In [27]:
import numpy as np

a = np.full((2,3), 5)
a

array([[5, 5, 5],
       [5, 5, 5]])

In [28]:
np.save("untitled.npy", a)

In [29]:
savedMatrix = np.load('untitled.npy')
savedMatrix

array([[5, 5, 5],
       [5, 5, 5]])

In [30]:
import numpy as np

f1=np. full((2,2),5)
print("\nf1 = \n",f1)

f2=np.full((2,2), 3)
print("\nf2 = \n", f2)

print("point to point multiplication = ",f1*f2)

print("point to point multiplication = ", np.dot(f1,f2))


f1 = 
 [[5 5]
 [5 5]]

f2 = 
 [[3 3]
 [3 3]]
point to point multiplication =  [[15 15]
 [15 15]]
point to point multiplication =  [[30 30]
 [30 30]]


In [31]:
#create a dictionary

StuDict={"Name": ["Aqsa","Esha", "Ayesha", "Ayra", "Arfa", "Afsa", "Abdul", "Saadia", "Abu Bakar","Atif"],
"ID": ["SID-1","SID-2", "SID-3", "SID-4", "SID-5","SID-6", "SID-7", "SID-8", "SID-9","SID-10"],
"Rol1_no": [1,2,3,4,5,6,7,8,9,10],
"Semester" : [7,7,7,7,6,6,6,5,8,8]}

StuDict

{'Name': ['Aqsa',
  'Esha',
  'Ayesha',
  'Ayra',
  'Arfa',
  'Afsa',
  'Abdul',
  'Saadia',
  'Abu Bakar',
  'Atif'],
 'ID': ['SID-1',
  'SID-2',
  'SID-3',
  'SID-4',
  'SID-5',
  'SID-6',
  'SID-7',
  'SID-8',
  'SID-9',
  'SID-10'],
 'Rol1_no': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'Semester': [7, 7, 7, 7, 6, 6, 6, 5, 8, 8]}

In [34]:
#convert into data frames

import pandas as pd

data=pd.DataFrame (StuDict)

print(data)

print("\n\nThe data type of above given syntax is :",type (data))

        Name      ID  Rol1_no  Semester
0       Aqsa   SID-1        1         7
1       Esha   SID-2        2         7
2     Ayesha   SID-3        3         7
3       Ayra   SID-4        4         7
4       Arfa   SID-5        5         6
5       Afsa   SID-6        6         6
6      Abdul   SID-7        7         6
7     Saadia   SID-8        8         5
8  Abu Bakar   SID-9        9         8
9       Atif  SID-10       10         8


The data type of above given syntax is : <class 'pandas.DataFrame'>


In [4]:
import pandas as pd

StuDict = {
    "Name": ["Aqsa","Esha","Ayesha","Ayra","Arfa","Afsa","Abdul","Saadia","Abu Bakar","Atif"],

    "ID": ["SID-1","SID-2","SID-3","SID-4","SID-5",
           "SID-6","SID-7","SID-8","SID-9","SID-10"],

    "Rol1_no": [1,2,3,4,5,6,7,8,9,10],

    "Semester": [7,7,7,7,6,6,6,5,8,8]
}

data = pd.DataFrame(StuDict)

print(data.describe())

        Rol1_no   Semester
count  10.00000  10.000000
mean    5.50000   6.700000
std     3.02765   0.948683
min     1.00000   5.000000
25%     3.25000   6.000000
50%     5.50000   7.000000
75%     7.75000   7.000000
max    10.00000   8.000000


In [5]:
import pandas as pd

StuDict = {
    "Name": ["Aqsa","Esha","Ayesha","Ayra","Arfa","Afsa","Abdul","Saadia","Abu Bakar","Atif"],

    "ID": ["SID-1","SID-2","SID-3","SID-4","SID-5",
           "SID-6","SID-7","SID-8","SID-9","SID-10"],

    "Rol1_no": [1,2,3,4,5,6,7,8,9,10],

    "Semester": [7,7,7,7,6,6,6,5,8,8]
}

data = pd.DataFrame(StuDict)
print(data.head())

     Name     ID  Rol1_no  Semester
0    Aqsa  SID-1        1         7
1    Esha  SID-2        2         7
2  Ayesha  SID-3        3         7
3    Ayra  SID-4        4         7
4    Arfa  SID-5        5         6


In [6]:
import pandas as pd

StuDict = {
    "Name": ["Aqsa","Esha","Ayesha","Ayra","Arfa","Afsa","Abdul","Saadia","Abu Bakar","Atif"],

    "ID": ["SID-1","SID-2","SID-3","SID-4","SID-5",
           "SID-6","SID-7","SID-8","SID-9","SID-10"],

    "Rol1_no": [1,2,3,4,5,6,7,8,9,10],

    "Semester": [7,7,7,7,6,6,6,5,8,8]
}

data = pd.DataFrame(StuDict)
print(data.tail())

        Name      ID  Rol1_no  Semester
5       Afsa   SID-6        6         6
6      Abdul   SID-7        7         6
7     Saadia   SID-8        8         5
8  Abu Bakar   SID-9        9         8
9       Atif  SID-10       10         8


In [7]:
import pandas as pd

StuDict = {
    "Name": ["Aqsa","Esha","Ayesha","Ayra","Arfa","Afsa","Abdul","Saadia","Abu Bakar","Atif"],

    "ID": ["SID-1","SID-2","SID-3","SID-4","SID-5",
           "SID-6","SID-7","SID-8","SID-9","SID-10"],

    "Rol1_no": [1,2,3,4,5,6,7,8,9,10],

    "Semester": [7,7,7,7,6,6,6,5,8,8]
}

data = pd.DataFrame(StuDict)
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      10 non-null     str  
 1   ID        10 non-null     str  
 2   Rol1_no   10 non-null     int64
 3   Semester  10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 452.0 bytes
None


In [8]:
import pandas as pd

StuDict = {
    "Name": ["Aqsa","Esha","Ayesha","Ayra","Arfa","Afsa","Abdul","Saadia","Abu Bakar","Atif"],

    "ID": ["SID-1","SID-2","SID-3","SID-4","SID-5",
           "SID-6","SID-7","SID-8","SID-9","SID-10"],

    "Rol1_no": [1,2,3,4,5,6,7,8,9,10],

    "Semester": [7,7,7,7,6,6,6,5,8,8]
}

data = pd.DataFrame(StuDict)
data.to_csv('student.csv')

In [9]:
df = pd.read_csv('student.csv')
df

,Unnamed: 0,Name,ID,Rol1_no,Semester
0,0,Aqsa,SID-1,1,7
1,1,Esha,SID-2,2,7
2,2,Ayesha,SID-3,3,7
3,3,Ayra,SID-4,4,7
4,4,Arfa,SID-5,5,6
5,5,Afsa,SID-6,6,6
6,6,Abdul,SID-7,7,6
7,7,Saadia,SID-8,8,5
8,8,Abu Bakar,SID-9,9,8
9,9,Atif,SID-10,10,8


In [10]:
import pandas as pd
df = pd.read_csv('student.csv')

print(f"Describe Function \n {df.describe()}, \n head Function \n {df.head()} \n tail Function \n {df.tail()}")
print(f"\n info Function \n {df.info()}")

Describe Function 
        Unnamed: 0   Rol1_no   Semester
count    10.00000  10.00000  10.000000
mean      4.50000   5.50000   6.700000
std       3.02765   3.02765   0.948683
min       0.00000   1.00000   5.000000
25%       2.25000   3.25000   6.000000
50%       4.50000   5.50000   7.000000
75%       6.75000   7.75000   7.000000
max       9.00000  10.00000   8.000000, 
 head Function 
    Unnamed: 0    Name     ID  Rol1_no  Semester
0           0    Aqsa  SID-1        1         7
1           1    Esha  SID-2        2         7
2           2  Ayesha  SID-3        3         7
3           3    Ayra  SID-4        4         7
4           4    Arfa  SID-5        5         6 
 tail Function 
    Unnamed: 0       Name      ID  Rol1_no  Semester
5           5       Afsa   SID-6        6         6
6           6      Abdul   SID-7        7         6
7           7     Saadia   SID-8        8         5
8           8  Abu Bakar   SID-9        9         8
9           9       Atif  SID-10       10   

In [11]:
import pandas as pd

df['Name']

0         Aqsa
1         Esha
2       Ayesha
3         Ayra
4         Arfa
5         Afsa
6        Abdul
7       Saadia
8    Abu Bakar
9         Atif
Name: Name, dtype: str

In [12]:
df['Name'][0]

'Aqsa'

In [17]:
df.loc[0, 'Name'] = 'Saddam'
print(df)

   Unnamed: 0       Name      ID  Rol1_no  Semester
0           0     Saddam   SID-1        1         7
1           1       Esha   SID-2        2         7
2           2     Ayesha   SID-3        3         7
3           3       Ayra   SID-4        4         7
4           4       Arfa   SID-5        5         6
5           5       Afsa   SID-6        6         6
6           6      Abdul   SID-7        7         6
7           7     Saadia   SID-8        8         5
8           8  Abu Bakar   SID-9        9         8
9           9       Atif  SID-10       10         8


In [18]:
df.columns

Index(['Unnamed: 0', 'Name', 'ID', 'Rol1_no', 'Semester'], dtype='str')

In [19]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [20]:
import pandas as pd
import numpy as np

s = pd.Series(np.random.rand(50))
print(s)
print(f"Using dtype: {s.dtype}")
print(f"Using type: {type(s)}")
print(f"Using Shape: {s.shape}")

0     0.359989
1     0.307258
2     0.916212
3     0.011666
4     0.057098
5     0.687598
6     0.163324
7     0.094060
8     0.481405
9     0.142867
10    0.687153
11    0.460133
12    0.837332
13    0.215173
14    0.374928
15    0.846992
16    0.971961
17    0.391273
18    0.891769
19    0.836747
20    0.292115
21    0.592194
22    0.315896
23    0.285622
24    0.757067
25    0.165595
26    0.066409
27    0.796221
28    0.643789
29    0.073574
30    0.468906
31    0.056753
32    0.755605
33    0.622177
34    0.443968
35    0.201001
36    0.685156
37    0.796420
38    0.969382
39    0.771039
40    0.443589
41    0.999470
42    0.788696
43    0.617885
44    0.163976
45    0.319877
46    0.104855
47    0.346506
48    0.369736
49    0.935507
dtype: float64
Using dtype: float64
Using type: <class 'pandas.Series'>
Using Shape: (50,)


In [24]:
import pandas as pd
import numpy as np

dataf = pd.DataFrame(np.random.rand(50,5))
print(dataf)
print(f"Using dtype: {s.dtype}")
print(f"Using type: {type(s)}")
print(f"Using Shape: {s.shape}")

           0         1         2         3         4
0   0.924053  0.903683  0.160403  0.005564  0.166831
1   0.438343  0.387345  0.254219  0.407040  0.913458
2   0.928850  0.735367  0.464558  0.505011  0.538190
3   0.790299  0.773828  0.777899  0.216679  0.804781
4   0.313211  0.359362  0.812915  0.370194  0.475069
5   0.580541  0.686162  0.946736  0.774571  0.740499
6   0.345007  0.288892  0.689581  0.142579  0.205244
7   0.943066  0.197014  0.306710  0.567900  0.842238
8   0.656544  0.701388  0.314993  0.042614  0.983650
9   0.375825  0.079208  0.870397  0.521206  0.484824
10  0.888392  0.579570  0.784135  0.969225  0.628243
11  0.813573  0.590359  0.265845  0.905195  0.205449
12  0.736353  0.222499  0.436199  0.793165  0.582178
13  0.994995  0.567911  0.380015  0.757567  0.074528
14  0.448727  0.485607  0.122719  0.291472  0.706334
15  0.469303  0.856733  0.148168  0.322028  0.072412
16  0.600154  0.261119  0.428723  0.525746  0.989875
17  0.859142  0.166327  0.219340  0.142855  0.

In [25]:
dataf.min()

0    0.014338
1    0.001067
2    0.001439
3    0.000772
4    0.046265
dtype: float64

In [26]:
dataf.max()

0    0.994995
1    0.992960
2    0.946736
3    0.969225
4    0.989875
dtype: float64

In [27]:
dataf.mean()

0    0.472987
1    0.537921
2    0.463448
3    0.473824
4    0.520481
dtype: float64

In [28]:
dataf[0].max()

np.float64(0.994994800136533)

In [29]:
d1 = dataf.to_numpy()
d1

array([[9.24053491e-01, 9.03682893e-01, 1.60403046e-01, 5.56413388e-03,
        1.66831096e-01],
       [4.38343338e-01, 3.87344639e-01, 2.54218900e-01, 4.07039619e-01,
        9.13458089e-01],
       [9.28850320e-01, 7.35366627e-01, 4.64558450e-01, 5.05010993e-01,
        5.38189729e-01],
       [7.90298541e-01, 7.73828433e-01, 7.77899423e-01, 2.16679176e-01,
        8.04781186e-01],
       [3.13210587e-01, 3.59361915e-01, 8.12915206e-01, 3.70194137e-01,
        4.75069427e-01],
       [5.80540863e-01, 6.86162162e-01, 9.46735744e-01, 7.74571151e-01,
        7.40499181e-01],
       [3.45007485e-01, 2.88891928e-01, 6.89581433e-01, 1.42579401e-01,
        2.05244285e-01],
       [9.43066310e-01, 1.97013815e-01, 3.06709918e-01, 5.67900075e-01,
        8.42238123e-01],
       [6.56543966e-01, 7.01387591e-01, 3.14993029e-01, 4.26140242e-02,
        9.83650422e-01],
       [3.75824806e-01, 7.92079890e-02, 8.70397284e-01, 5.21206179e-01,
        4.84824066e-01],
       [8.88392435e-01, 5.7957

In [30]:
d1.T

array([[9.24053491e-01, 4.38343338e-01, 9.28850320e-01, 7.90298541e-01,
        3.13210587e-01, 5.80540863e-01, 3.45007485e-01, 9.43066310e-01,
        6.56543966e-01, 3.75824806e-01, 8.88392435e-01, 8.13573311e-01,
        7.36352967e-01, 9.94994800e-01, 4.48727466e-01, 4.69303453e-01,
        6.00154195e-01, 8.59141631e-01, 7.15280870e-02, 2.20654946e-01,
        5.03905394e-02, 1.01332318e-01, 3.36276211e-01, 2.15148393e-01,
        7.24426403e-01, 2.64178895e-01, 7.78593519e-02, 3.89782387e-01,
        6.81176267e-01, 7.63967087e-02, 1.51818333e-01, 4.50093550e-01,
        1.87260482e-01, 8.47491824e-02, 9.91379685e-01, 5.57751763e-01,
        3.50577376e-01, 8.89290864e-01, 2.57681713e-01, 6.94907938e-01,
        4.55194224e-01, 3.62933687e-01, 1.94142074e-01, 4.88244879e-02,
        7.68712234e-01, 7.47228688e-02, 1.43376100e-02, 6.51703536e-01,
        6.03343366e-01, 5.44415673e-01],
       [9.03682893e-01, 3.87344639e-01, 7.35366627e-01, 7.73828433e-01,
        3.59361915e-01,

In [31]:
dataf.columns = ['A', 'B', 'C', 'D', 'E']
dataf

,A,B,C,D,E
0,0.924053,0.903683,0.160403,0.005564,0.166831
1,0.438343,0.387345,0.254219,0.407040,0.913458
2,0.928850,0.735367,0.464558,0.505011,0.538190
3,0.790299,0.773828,0.777899,0.216679,0.804781
4,0.313211,0.359362,0.812915,0.370194,0.475069
5,0.580541,0.686162,0.946736,0.774571,0.740499
6,0.345007,0.288892,0.689581,0.142579,0.205244
7,0.943066,0.197014,0.306710,0.567900,0.842238
8,0.656544,0.701388,0.314993,0.042614,0.983650
9,0.375825,0.079208,0.870397,0.521206,0.484824


In [32]:
dataf[['B', 'C']]

,B,C
0,0.903683,0.160403
1,0.387345,0.254219
2,0.735367,0.464558
3,0.773828,0.777899
4,0.359362,0.812915
5,0.686162,0.946736
6,0.288892,0.689581
7,0.197014,0.306710
8,0.701388,0.314993
9,0.079208,0.870397


In [33]:
dataf.iloc[:, 0:2]   # : means all rows and 0:2 means cloumns till 2 

,A,B
0,0.924053,0.903683
1,0.438343,0.387345
2,0.928850,0.735367
3,0.790299,0.773828
4,0.313211,0.359362
5,0.580541,0.686162
6,0.345007,0.288892
7,0.943066,0.197014
8,0.656544,0.701388
9,0.375825,0.079208


In [34]:
dataf.loc[:, 'A':'C'] # loc function use to specify the columns label or name

,A,B,C
0,0.924053,0.903683,0.160403
1,0.438343,0.387345,0.254219
2,0.928850,0.735367,0.464558
3,0.790299,0.773828,0.777899
4,0.313211,0.359362,0.812915
5,0.580541,0.686162,0.946736
6,0.345007,0.288892,0.689581
7,0.943066,0.197014,0.306710
8,0.656544,0.701388,0.314993
9,0.375825,0.079208,0.870397


In [35]:
dataf.iloc[0:12, 2:4]

,C,D
0,0.160403,0.005564
1,0.254219,0.407040
2,0.464558,0.505011
3,0.777899,0.216679
4,0.812915,0.370194
5,0.946736,0.774571
6,0.689581,0.142579
7,0.306710,0.567900
8,0.314993,0.042614
9,0.870397,0.521206
